---
title: "p8105_hw5_ys3298"
author: "Yimeng SHANG"
date: "11/1/2019"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```


# PROBLEM1

```{r echo=FALSE}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

```

```{r echo=FALSE}
#Write a function 
missing_value = function(vec) {
  if (is.numeric(vec)) {
    m = round(mean(vec, na.rm = TRUE), 1)
    output = vec %>% replace_na(m)
  } else if (is.character(vec)) {
    output = vec %>% replace_na("virginica")
  } else {
    stop("Error in type")
  }
  output
}

#missing_value(iris_with_missing$Sepal.Length)
#missing_value(iris_with_missing$Sepal.Width)
#missing_value(iris_with_missing$Petal.Length)
#missing_value(iris_with_missing$Petal.Width)
#missing_value(iris_with_missing$Species)

#Apply this function to the columns of iris_with_missing using a map statement
map(iris_with_missing, missing_value)
```


# PROBLEM2

```{r echo=TRUE}
# create a tidy dataframe
filename = list.files("./data") 
data_path = paste("./data", filename, sep = "/")

names = data_frame(filename = filename)

data =
  data_path %>%
  map(read_csv) %>%     
  reduce(rbind) %>% 
  cbind(names) %>% 
  separate(col = filename, into = c("group","ID_csv"), sep = "_") %>% 
  mutate(ID = str_replace(ID_csv,".csv","")) %>% 
  select( group, ID, everything()) %>% 
  select(-ID_csv) %>% 
  janitor::clean_names() %>% 
  knitr::kable()
```

```{r echo=TRUE}
# plot


```


# PROBLEM3

```{r echo=TRUE}
model = function(beta1=0) {
  x = rnorm(30, 0, 1)
  epi = rnorm(30, 0, sd = 50)
  y = 2 + beta1 * x + epi
  data = tibble(x=x,y=y)
  
  ls_fit = lm(y~x, data) %>% 
    broom::tidy()
  return(tibble(beta1 = ls_fit$estimate[[2]], p = ls_fit$p.value[2]))
}

sim_results = 
  rerun(10000, model(0)) %>%  ## rerun
  bind_rows()


 

```


